services:
  pyroscope:
    image: grafana/pyroscope:latest
    ports:
    - 4040:4040

  grafana:
    image: grafana/grafana:latest
    environment:
    - GF_PLUGINS_PREINSTALL_SYNC=grafana-pyroscope-app
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
    - ./grafana-provisioning:/etc/grafana/provisioning
    ports:
    - 3000:3000

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: DRAGON
      POSTGRES_PASSWORD: DRAGON
      POSTGRES_DB: PAYMENT_GATEWAY
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U DRAGON -d PAYMENT_GATEWAY"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  migrate:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.migrate
    volumes:
      - ./docker.env:/app/docker.env
      - ./pkg/database/migrations:/app/pkg/database/migrations
    container_name: migrate
    env_file: ./docker.env

    environment:
      DB_URL: postgres://DRAGON:DRAGON@postgres/PAYMENT_GATEWAY
    networks:
      - app_network
    depends_on:
      postgres:
        condition: service_started

  server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.server
    volumes:
      - ./docker.env:/app/docker.env
    container_name: server
    env_file: ./docker.env
    ports:
    - "50051:50051"
    networks:
      - app_network
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_started

  client:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.client
    ports:
      - "5000:5000"
    volumes:
      - ./docker.env:/app/docker.env
    env_file: ./docker.env
    container_name: client
    networks:
      - app_network
    depends_on:
      server:
        condition: service_started

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
