// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pb/withdraw_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=internal/pb/withdraw_grpc.pb.go -destination=internal/pb/mocks/withdraw_grpc_mock.go
//

// Package mock_pb is a generated GoMock package.
package mock_pb

import (
	pb "MamangRust/paymentgatewaygrpc/internal/pb"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockWithdrawServiceClient is a mock of WithdrawServiceClient interface.
type MockWithdrawServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawServiceClientMockRecorder
	isgomock struct{}
}

// MockWithdrawServiceClientMockRecorder is the mock recorder for MockWithdrawServiceClient.
type MockWithdrawServiceClientMockRecorder struct {
	mock *MockWithdrawServiceClient
}

// NewMockWithdrawServiceClient creates a new mock instance.
func NewMockWithdrawServiceClient(ctrl *gomock.Controller) *MockWithdrawServiceClient {
	mock := &MockWithdrawServiceClient{ctrl: ctrl}
	mock.recorder = &MockWithdrawServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawServiceClient) EXPECT() *MockWithdrawServiceClientMockRecorder {
	return m.recorder
}

// CreateWithdraw mocks base method.
func (m *MockWithdrawServiceClient) CreateWithdraw(ctx context.Context, in *pb.CreateWithdrawRequest, opts ...grpc.CallOption) (*pb.ApiResponseWithdraw, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateWithdraw", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseWithdraw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithdraw indicates an expected call of CreateWithdraw.
func (mr *MockWithdrawServiceClientMockRecorder) CreateWithdraw(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithdraw", reflect.TypeOf((*MockWithdrawServiceClient)(nil).CreateWithdraw), varargs...)
}

// DeleteAllWithdrawPermanent mocks base method.
func (m *MockWithdrawServiceClient) DeleteAllWithdrawPermanent(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*pb.ApiResponseWithdrawAll, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteAllWithdrawPermanent", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawAll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAllWithdrawPermanent indicates an expected call of DeleteAllWithdrawPermanent.
func (mr *MockWithdrawServiceClientMockRecorder) DeleteAllWithdrawPermanent(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllWithdrawPermanent", reflect.TypeOf((*MockWithdrawServiceClient)(nil).DeleteAllWithdrawPermanent), varargs...)
}

// DeleteWithdrawPermanent mocks base method.
func (m *MockWithdrawServiceClient) DeleteWithdrawPermanent(ctx context.Context, in *pb.FindByIdWithdrawRequest, opts ...grpc.CallOption) (*pb.ApiResponseWithdrawDelete, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteWithdrawPermanent", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawDelete)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteWithdrawPermanent indicates an expected call of DeleteWithdrawPermanent.
func (mr *MockWithdrawServiceClientMockRecorder) DeleteWithdrawPermanent(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWithdrawPermanent", reflect.TypeOf((*MockWithdrawServiceClient)(nil).DeleteWithdrawPermanent), varargs...)
}

// FindAllWithdraw mocks base method.
func (m *MockWithdrawServiceClient) FindAllWithdraw(ctx context.Context, in *pb.FindAllWithdrawRequest, opts ...grpc.CallOption) (*pb.ApiResponsePaginationWithdraw, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindAllWithdraw", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponsePaginationWithdraw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllWithdraw indicates an expected call of FindAllWithdraw.
func (mr *MockWithdrawServiceClientMockRecorder) FindAllWithdraw(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllWithdraw", reflect.TypeOf((*MockWithdrawServiceClient)(nil).FindAllWithdraw), varargs...)
}

// FindAllWithdrawByCardNumber mocks base method.
func (m *MockWithdrawServiceClient) FindAllWithdrawByCardNumber(ctx context.Context, in *pb.FindAllWithdrawByCardNumberRequest, opts ...grpc.CallOption) (*pb.ApiResponsePaginationWithdraw, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindAllWithdrawByCardNumber", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponsePaginationWithdraw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllWithdrawByCardNumber indicates an expected call of FindAllWithdrawByCardNumber.
func (mr *MockWithdrawServiceClientMockRecorder) FindAllWithdrawByCardNumber(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllWithdrawByCardNumber", reflect.TypeOf((*MockWithdrawServiceClient)(nil).FindAllWithdrawByCardNumber), varargs...)
}

// FindByActive mocks base method.
func (m *MockWithdrawServiceClient) FindByActive(ctx context.Context, in *pb.FindAllWithdrawRequest, opts ...grpc.CallOption) (*pb.ApiResponsePaginationWithdrawDeleteAt, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindByActive", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponsePaginationWithdrawDeleteAt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByActive indicates an expected call of FindByActive.
func (mr *MockWithdrawServiceClientMockRecorder) FindByActive(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByActive", reflect.TypeOf((*MockWithdrawServiceClient)(nil).FindByActive), varargs...)
}

// FindByCardNumber mocks base method.
func (m *MockWithdrawServiceClient) FindByCardNumber(ctx context.Context, in *pb.FindByCardNumberRequest, opts ...grpc.CallOption) (*pb.ApiResponsesWithdraw, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindByCardNumber", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponsesWithdraw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCardNumber indicates an expected call of FindByCardNumber.
func (mr *MockWithdrawServiceClientMockRecorder) FindByCardNumber(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCardNumber", reflect.TypeOf((*MockWithdrawServiceClient)(nil).FindByCardNumber), varargs...)
}

// FindByIdWithdraw mocks base method.
func (m *MockWithdrawServiceClient) FindByIdWithdraw(ctx context.Context, in *pb.FindByIdWithdrawRequest, opts ...grpc.CallOption) (*pb.ApiResponseWithdraw, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindByIdWithdraw", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseWithdraw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIdWithdraw indicates an expected call of FindByIdWithdraw.
func (mr *MockWithdrawServiceClientMockRecorder) FindByIdWithdraw(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIdWithdraw", reflect.TypeOf((*MockWithdrawServiceClient)(nil).FindByIdWithdraw), varargs...)
}

// FindByTrashed mocks base method.
func (m *MockWithdrawServiceClient) FindByTrashed(ctx context.Context, in *pb.FindAllWithdrawRequest, opts ...grpc.CallOption) (*pb.ApiResponsePaginationWithdrawDeleteAt, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindByTrashed", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponsePaginationWithdrawDeleteAt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTrashed indicates an expected call of FindByTrashed.
func (mr *MockWithdrawServiceClientMockRecorder) FindByTrashed(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTrashed", reflect.TypeOf((*MockWithdrawServiceClient)(nil).FindByTrashed), varargs...)
}

// FindMonthlyWithdrawStatusFailed mocks base method.
func (m *MockWithdrawServiceClient) FindMonthlyWithdrawStatusFailed(ctx context.Context, in *pb.FindMonthlyWithdrawStatus, opts ...grpc.CallOption) (*pb.ApiResponseWithdrawMonthStatusFailed, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindMonthlyWithdrawStatusFailed", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawMonthStatusFailed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMonthlyWithdrawStatusFailed indicates an expected call of FindMonthlyWithdrawStatusFailed.
func (mr *MockWithdrawServiceClientMockRecorder) FindMonthlyWithdrawStatusFailed(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMonthlyWithdrawStatusFailed", reflect.TypeOf((*MockWithdrawServiceClient)(nil).FindMonthlyWithdrawStatusFailed), varargs...)
}

// FindMonthlyWithdrawStatusFailedCardNumber mocks base method.
func (m *MockWithdrawServiceClient) FindMonthlyWithdrawStatusFailedCardNumber(ctx context.Context, in *pb.FindMonthlyWithdrawStatusCardNumber, opts ...grpc.CallOption) (*pb.ApiResponseWithdrawMonthStatusFailed, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindMonthlyWithdrawStatusFailedCardNumber", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawMonthStatusFailed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMonthlyWithdrawStatusFailedCardNumber indicates an expected call of FindMonthlyWithdrawStatusFailedCardNumber.
func (mr *MockWithdrawServiceClientMockRecorder) FindMonthlyWithdrawStatusFailedCardNumber(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMonthlyWithdrawStatusFailedCardNumber", reflect.TypeOf((*MockWithdrawServiceClient)(nil).FindMonthlyWithdrawStatusFailedCardNumber), varargs...)
}

// FindMonthlyWithdrawStatusSuccess mocks base method.
func (m *MockWithdrawServiceClient) FindMonthlyWithdrawStatusSuccess(ctx context.Context, in *pb.FindMonthlyWithdrawStatus, opts ...grpc.CallOption) (*pb.ApiResponseWithdrawMonthStatusSuccess, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindMonthlyWithdrawStatusSuccess", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawMonthStatusSuccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMonthlyWithdrawStatusSuccess indicates an expected call of FindMonthlyWithdrawStatusSuccess.
func (mr *MockWithdrawServiceClientMockRecorder) FindMonthlyWithdrawStatusSuccess(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMonthlyWithdrawStatusSuccess", reflect.TypeOf((*MockWithdrawServiceClient)(nil).FindMonthlyWithdrawStatusSuccess), varargs...)
}

// FindMonthlyWithdrawStatusSuccessCardNumber mocks base method.
func (m *MockWithdrawServiceClient) FindMonthlyWithdrawStatusSuccessCardNumber(ctx context.Context, in *pb.FindMonthlyWithdrawStatusCardNumber, opts ...grpc.CallOption) (*pb.ApiResponseWithdrawMonthStatusSuccess, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindMonthlyWithdrawStatusSuccessCardNumber", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawMonthStatusSuccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMonthlyWithdrawStatusSuccessCardNumber indicates an expected call of FindMonthlyWithdrawStatusSuccessCardNumber.
func (mr *MockWithdrawServiceClientMockRecorder) FindMonthlyWithdrawStatusSuccessCardNumber(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMonthlyWithdrawStatusSuccessCardNumber", reflect.TypeOf((*MockWithdrawServiceClient)(nil).FindMonthlyWithdrawStatusSuccessCardNumber), varargs...)
}

// FindMonthlyWithdraws mocks base method.
func (m *MockWithdrawServiceClient) FindMonthlyWithdraws(ctx context.Context, in *pb.FindYearWithdrawStatus, opts ...grpc.CallOption) (*pb.ApiResponseWithdrawMonthAmount, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindMonthlyWithdraws", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawMonthAmount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMonthlyWithdraws indicates an expected call of FindMonthlyWithdraws.
func (mr *MockWithdrawServiceClientMockRecorder) FindMonthlyWithdraws(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMonthlyWithdraws", reflect.TypeOf((*MockWithdrawServiceClient)(nil).FindMonthlyWithdraws), varargs...)
}

// FindMonthlyWithdrawsByCardNumber mocks base method.
func (m *MockWithdrawServiceClient) FindMonthlyWithdrawsByCardNumber(ctx context.Context, in *pb.FindYearWithdrawCardNumber, opts ...grpc.CallOption) (*pb.ApiResponseWithdrawMonthAmount, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindMonthlyWithdrawsByCardNumber", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawMonthAmount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMonthlyWithdrawsByCardNumber indicates an expected call of FindMonthlyWithdrawsByCardNumber.
func (mr *MockWithdrawServiceClientMockRecorder) FindMonthlyWithdrawsByCardNumber(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMonthlyWithdrawsByCardNumber", reflect.TypeOf((*MockWithdrawServiceClient)(nil).FindMonthlyWithdrawsByCardNumber), varargs...)
}

// FindYearlyWithdrawStatusFailed mocks base method.
func (m *MockWithdrawServiceClient) FindYearlyWithdrawStatusFailed(ctx context.Context, in *pb.FindYearWithdrawStatus, opts ...grpc.CallOption) (*pb.ApiResponseWithdrawYearStatusFailed, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindYearlyWithdrawStatusFailed", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawYearStatusFailed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindYearlyWithdrawStatusFailed indicates an expected call of FindYearlyWithdrawStatusFailed.
func (mr *MockWithdrawServiceClientMockRecorder) FindYearlyWithdrawStatusFailed(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindYearlyWithdrawStatusFailed", reflect.TypeOf((*MockWithdrawServiceClient)(nil).FindYearlyWithdrawStatusFailed), varargs...)
}

// FindYearlyWithdrawStatusFailedCardNumber mocks base method.
func (m *MockWithdrawServiceClient) FindYearlyWithdrawStatusFailedCardNumber(ctx context.Context, in *pb.FindYearWithdrawStatusCardNumber, opts ...grpc.CallOption) (*pb.ApiResponseWithdrawYearStatusFailed, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindYearlyWithdrawStatusFailedCardNumber", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawYearStatusFailed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindYearlyWithdrawStatusFailedCardNumber indicates an expected call of FindYearlyWithdrawStatusFailedCardNumber.
func (mr *MockWithdrawServiceClientMockRecorder) FindYearlyWithdrawStatusFailedCardNumber(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindYearlyWithdrawStatusFailedCardNumber", reflect.TypeOf((*MockWithdrawServiceClient)(nil).FindYearlyWithdrawStatusFailedCardNumber), varargs...)
}

// FindYearlyWithdrawStatusSuccess mocks base method.
func (m *MockWithdrawServiceClient) FindYearlyWithdrawStatusSuccess(ctx context.Context, in *pb.FindYearWithdrawStatus, opts ...grpc.CallOption) (*pb.ApiResponseWithdrawYearStatusSuccess, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindYearlyWithdrawStatusSuccess", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawYearStatusSuccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindYearlyWithdrawStatusSuccess indicates an expected call of FindYearlyWithdrawStatusSuccess.
func (mr *MockWithdrawServiceClientMockRecorder) FindYearlyWithdrawStatusSuccess(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindYearlyWithdrawStatusSuccess", reflect.TypeOf((*MockWithdrawServiceClient)(nil).FindYearlyWithdrawStatusSuccess), varargs...)
}

// FindYearlyWithdrawStatusSuccessCardNumber mocks base method.
func (m *MockWithdrawServiceClient) FindYearlyWithdrawStatusSuccessCardNumber(ctx context.Context, in *pb.FindYearWithdrawStatusCardNumber, opts ...grpc.CallOption) (*pb.ApiResponseWithdrawYearStatusSuccess, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindYearlyWithdrawStatusSuccessCardNumber", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawYearStatusSuccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindYearlyWithdrawStatusSuccessCardNumber indicates an expected call of FindYearlyWithdrawStatusSuccessCardNumber.
func (mr *MockWithdrawServiceClientMockRecorder) FindYearlyWithdrawStatusSuccessCardNumber(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindYearlyWithdrawStatusSuccessCardNumber", reflect.TypeOf((*MockWithdrawServiceClient)(nil).FindYearlyWithdrawStatusSuccessCardNumber), varargs...)
}

// FindYearlyWithdraws mocks base method.
func (m *MockWithdrawServiceClient) FindYearlyWithdraws(ctx context.Context, in *pb.FindYearWithdrawStatus, opts ...grpc.CallOption) (*pb.ApiResponseWithdrawYearAmount, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindYearlyWithdraws", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawYearAmount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindYearlyWithdraws indicates an expected call of FindYearlyWithdraws.
func (mr *MockWithdrawServiceClientMockRecorder) FindYearlyWithdraws(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindYearlyWithdraws", reflect.TypeOf((*MockWithdrawServiceClient)(nil).FindYearlyWithdraws), varargs...)
}

// FindYearlyWithdrawsByCardNumber mocks base method.
func (m *MockWithdrawServiceClient) FindYearlyWithdrawsByCardNumber(ctx context.Context, in *pb.FindYearWithdrawCardNumber, opts ...grpc.CallOption) (*pb.ApiResponseWithdrawYearAmount, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FindYearlyWithdrawsByCardNumber", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawYearAmount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindYearlyWithdrawsByCardNumber indicates an expected call of FindYearlyWithdrawsByCardNumber.
func (mr *MockWithdrawServiceClientMockRecorder) FindYearlyWithdrawsByCardNumber(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindYearlyWithdrawsByCardNumber", reflect.TypeOf((*MockWithdrawServiceClient)(nil).FindYearlyWithdrawsByCardNumber), varargs...)
}

// RestoreAllWithdraw mocks base method.
func (m *MockWithdrawServiceClient) RestoreAllWithdraw(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*pb.ApiResponseWithdrawAll, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RestoreAllWithdraw", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawAll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreAllWithdraw indicates an expected call of RestoreAllWithdraw.
func (mr *MockWithdrawServiceClientMockRecorder) RestoreAllWithdraw(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreAllWithdraw", reflect.TypeOf((*MockWithdrawServiceClient)(nil).RestoreAllWithdraw), varargs...)
}

// RestoreWithdraw mocks base method.
func (m *MockWithdrawServiceClient) RestoreWithdraw(ctx context.Context, in *pb.FindByIdWithdrawRequest, opts ...grpc.CallOption) (*pb.ApiResponseWithdraw, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RestoreWithdraw", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseWithdraw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreWithdraw indicates an expected call of RestoreWithdraw.
func (mr *MockWithdrawServiceClientMockRecorder) RestoreWithdraw(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreWithdraw", reflect.TypeOf((*MockWithdrawServiceClient)(nil).RestoreWithdraw), varargs...)
}

// TrashedWithdraw mocks base method.
func (m *MockWithdrawServiceClient) TrashedWithdraw(ctx context.Context, in *pb.FindByIdWithdrawRequest, opts ...grpc.CallOption) (*pb.ApiResponseWithdraw, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TrashedWithdraw", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseWithdraw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TrashedWithdraw indicates an expected call of TrashedWithdraw.
func (mr *MockWithdrawServiceClientMockRecorder) TrashedWithdraw(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrashedWithdraw", reflect.TypeOf((*MockWithdrawServiceClient)(nil).TrashedWithdraw), varargs...)
}

// UpdateWithdraw mocks base method.
func (m *MockWithdrawServiceClient) UpdateWithdraw(ctx context.Context, in *pb.UpdateWithdrawRequest, opts ...grpc.CallOption) (*pb.ApiResponseWithdraw, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateWithdraw", varargs...)
	ret0, _ := ret[0].(*pb.ApiResponseWithdraw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWithdraw indicates an expected call of UpdateWithdraw.
func (mr *MockWithdrawServiceClientMockRecorder) UpdateWithdraw(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithdraw", reflect.TypeOf((*MockWithdrawServiceClient)(nil).UpdateWithdraw), varargs...)
}

// MockWithdrawServiceServer is a mock of WithdrawServiceServer interface.
type MockWithdrawServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockWithdrawServiceServerMockRecorder
	isgomock struct{}
}

// MockWithdrawServiceServerMockRecorder is the mock recorder for MockWithdrawServiceServer.
type MockWithdrawServiceServerMockRecorder struct {
	mock *MockWithdrawServiceServer
}

// NewMockWithdrawServiceServer creates a new mock instance.
func NewMockWithdrawServiceServer(ctrl *gomock.Controller) *MockWithdrawServiceServer {
	mock := &MockWithdrawServiceServer{ctrl: ctrl}
	mock.recorder = &MockWithdrawServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWithdrawServiceServer) EXPECT() *MockWithdrawServiceServerMockRecorder {
	return m.recorder
}

// CreateWithdraw mocks base method.
func (m *MockWithdrawServiceServer) CreateWithdraw(arg0 context.Context, arg1 *pb.CreateWithdrawRequest) (*pb.ApiResponseWithdraw, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithdraw", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseWithdraw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWithdraw indicates an expected call of CreateWithdraw.
func (mr *MockWithdrawServiceServerMockRecorder) CreateWithdraw(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithdraw", reflect.TypeOf((*MockWithdrawServiceServer)(nil).CreateWithdraw), arg0, arg1)
}

// DeleteAllWithdrawPermanent mocks base method.
func (m *MockWithdrawServiceServer) DeleteAllWithdrawPermanent(arg0 context.Context, arg1 *emptypb.Empty) (*pb.ApiResponseWithdrawAll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllWithdrawPermanent", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawAll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAllWithdrawPermanent indicates an expected call of DeleteAllWithdrawPermanent.
func (mr *MockWithdrawServiceServerMockRecorder) DeleteAllWithdrawPermanent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllWithdrawPermanent", reflect.TypeOf((*MockWithdrawServiceServer)(nil).DeleteAllWithdrawPermanent), arg0, arg1)
}

// DeleteWithdrawPermanent mocks base method.
func (m *MockWithdrawServiceServer) DeleteWithdrawPermanent(arg0 context.Context, arg1 *pb.FindByIdWithdrawRequest) (*pb.ApiResponseWithdrawDelete, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWithdrawPermanent", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawDelete)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteWithdrawPermanent indicates an expected call of DeleteWithdrawPermanent.
func (mr *MockWithdrawServiceServerMockRecorder) DeleteWithdrawPermanent(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWithdrawPermanent", reflect.TypeOf((*MockWithdrawServiceServer)(nil).DeleteWithdrawPermanent), arg0, arg1)
}

// FindAllWithdraw mocks base method.
func (m *MockWithdrawServiceServer) FindAllWithdraw(arg0 context.Context, arg1 *pb.FindAllWithdrawRequest) (*pb.ApiResponsePaginationWithdraw, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllWithdraw", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponsePaginationWithdraw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllWithdraw indicates an expected call of FindAllWithdraw.
func (mr *MockWithdrawServiceServerMockRecorder) FindAllWithdraw(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllWithdraw", reflect.TypeOf((*MockWithdrawServiceServer)(nil).FindAllWithdraw), arg0, arg1)
}

// FindAllWithdrawByCardNumber mocks base method.
func (m *MockWithdrawServiceServer) FindAllWithdrawByCardNumber(arg0 context.Context, arg1 *pb.FindAllWithdrawByCardNumberRequest) (*pb.ApiResponsePaginationWithdraw, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllWithdrawByCardNumber", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponsePaginationWithdraw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllWithdrawByCardNumber indicates an expected call of FindAllWithdrawByCardNumber.
func (mr *MockWithdrawServiceServerMockRecorder) FindAllWithdrawByCardNumber(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllWithdrawByCardNumber", reflect.TypeOf((*MockWithdrawServiceServer)(nil).FindAllWithdrawByCardNumber), arg0, arg1)
}

// FindByActive mocks base method.
func (m *MockWithdrawServiceServer) FindByActive(arg0 context.Context, arg1 *pb.FindAllWithdrawRequest) (*pb.ApiResponsePaginationWithdrawDeleteAt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByActive", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponsePaginationWithdrawDeleteAt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByActive indicates an expected call of FindByActive.
func (mr *MockWithdrawServiceServerMockRecorder) FindByActive(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByActive", reflect.TypeOf((*MockWithdrawServiceServer)(nil).FindByActive), arg0, arg1)
}

// FindByCardNumber mocks base method.
func (m *MockWithdrawServiceServer) FindByCardNumber(arg0 context.Context, arg1 *pb.FindByCardNumberRequest) (*pb.ApiResponsesWithdraw, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByCardNumber", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponsesWithdraw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByCardNumber indicates an expected call of FindByCardNumber.
func (mr *MockWithdrawServiceServerMockRecorder) FindByCardNumber(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByCardNumber", reflect.TypeOf((*MockWithdrawServiceServer)(nil).FindByCardNumber), arg0, arg1)
}

// FindByIdWithdraw mocks base method.
func (m *MockWithdrawServiceServer) FindByIdWithdraw(arg0 context.Context, arg1 *pb.FindByIdWithdrawRequest) (*pb.ApiResponseWithdraw, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIdWithdraw", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseWithdraw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIdWithdraw indicates an expected call of FindByIdWithdraw.
func (mr *MockWithdrawServiceServerMockRecorder) FindByIdWithdraw(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIdWithdraw", reflect.TypeOf((*MockWithdrawServiceServer)(nil).FindByIdWithdraw), arg0, arg1)
}

// FindByTrashed mocks base method.
func (m *MockWithdrawServiceServer) FindByTrashed(arg0 context.Context, arg1 *pb.FindAllWithdrawRequest) (*pb.ApiResponsePaginationWithdrawDeleteAt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTrashed", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponsePaginationWithdrawDeleteAt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTrashed indicates an expected call of FindByTrashed.
func (mr *MockWithdrawServiceServerMockRecorder) FindByTrashed(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTrashed", reflect.TypeOf((*MockWithdrawServiceServer)(nil).FindByTrashed), arg0, arg1)
}

// FindMonthlyWithdrawStatusFailed mocks base method.
func (m *MockWithdrawServiceServer) FindMonthlyWithdrawStatusFailed(arg0 context.Context, arg1 *pb.FindMonthlyWithdrawStatus) (*pb.ApiResponseWithdrawMonthStatusFailed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMonthlyWithdrawStatusFailed", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawMonthStatusFailed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMonthlyWithdrawStatusFailed indicates an expected call of FindMonthlyWithdrawStatusFailed.
func (mr *MockWithdrawServiceServerMockRecorder) FindMonthlyWithdrawStatusFailed(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMonthlyWithdrawStatusFailed", reflect.TypeOf((*MockWithdrawServiceServer)(nil).FindMonthlyWithdrawStatusFailed), arg0, arg1)
}

// FindMonthlyWithdrawStatusFailedCardNumber mocks base method.
func (m *MockWithdrawServiceServer) FindMonthlyWithdrawStatusFailedCardNumber(arg0 context.Context, arg1 *pb.FindMonthlyWithdrawStatusCardNumber) (*pb.ApiResponseWithdrawMonthStatusFailed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMonthlyWithdrawStatusFailedCardNumber", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawMonthStatusFailed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMonthlyWithdrawStatusFailedCardNumber indicates an expected call of FindMonthlyWithdrawStatusFailedCardNumber.
func (mr *MockWithdrawServiceServerMockRecorder) FindMonthlyWithdrawStatusFailedCardNumber(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMonthlyWithdrawStatusFailedCardNumber", reflect.TypeOf((*MockWithdrawServiceServer)(nil).FindMonthlyWithdrawStatusFailedCardNumber), arg0, arg1)
}

// FindMonthlyWithdrawStatusSuccess mocks base method.
func (m *MockWithdrawServiceServer) FindMonthlyWithdrawStatusSuccess(arg0 context.Context, arg1 *pb.FindMonthlyWithdrawStatus) (*pb.ApiResponseWithdrawMonthStatusSuccess, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMonthlyWithdrawStatusSuccess", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawMonthStatusSuccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMonthlyWithdrawStatusSuccess indicates an expected call of FindMonthlyWithdrawStatusSuccess.
func (mr *MockWithdrawServiceServerMockRecorder) FindMonthlyWithdrawStatusSuccess(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMonthlyWithdrawStatusSuccess", reflect.TypeOf((*MockWithdrawServiceServer)(nil).FindMonthlyWithdrawStatusSuccess), arg0, arg1)
}

// FindMonthlyWithdrawStatusSuccessCardNumber mocks base method.
func (m *MockWithdrawServiceServer) FindMonthlyWithdrawStatusSuccessCardNumber(arg0 context.Context, arg1 *pb.FindMonthlyWithdrawStatusCardNumber) (*pb.ApiResponseWithdrawMonthStatusSuccess, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMonthlyWithdrawStatusSuccessCardNumber", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawMonthStatusSuccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMonthlyWithdrawStatusSuccessCardNumber indicates an expected call of FindMonthlyWithdrawStatusSuccessCardNumber.
func (mr *MockWithdrawServiceServerMockRecorder) FindMonthlyWithdrawStatusSuccessCardNumber(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMonthlyWithdrawStatusSuccessCardNumber", reflect.TypeOf((*MockWithdrawServiceServer)(nil).FindMonthlyWithdrawStatusSuccessCardNumber), arg0, arg1)
}

// FindMonthlyWithdraws mocks base method.
func (m *MockWithdrawServiceServer) FindMonthlyWithdraws(arg0 context.Context, arg1 *pb.FindYearWithdrawStatus) (*pb.ApiResponseWithdrawMonthAmount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMonthlyWithdraws", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawMonthAmount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMonthlyWithdraws indicates an expected call of FindMonthlyWithdraws.
func (mr *MockWithdrawServiceServerMockRecorder) FindMonthlyWithdraws(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMonthlyWithdraws", reflect.TypeOf((*MockWithdrawServiceServer)(nil).FindMonthlyWithdraws), arg0, arg1)
}

// FindMonthlyWithdrawsByCardNumber mocks base method.
func (m *MockWithdrawServiceServer) FindMonthlyWithdrawsByCardNumber(arg0 context.Context, arg1 *pb.FindYearWithdrawCardNumber) (*pb.ApiResponseWithdrawMonthAmount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindMonthlyWithdrawsByCardNumber", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawMonthAmount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindMonthlyWithdrawsByCardNumber indicates an expected call of FindMonthlyWithdrawsByCardNumber.
func (mr *MockWithdrawServiceServerMockRecorder) FindMonthlyWithdrawsByCardNumber(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindMonthlyWithdrawsByCardNumber", reflect.TypeOf((*MockWithdrawServiceServer)(nil).FindMonthlyWithdrawsByCardNumber), arg0, arg1)
}

// FindYearlyWithdrawStatusFailed mocks base method.
func (m *MockWithdrawServiceServer) FindYearlyWithdrawStatusFailed(arg0 context.Context, arg1 *pb.FindYearWithdrawStatus) (*pb.ApiResponseWithdrawYearStatusFailed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindYearlyWithdrawStatusFailed", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawYearStatusFailed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindYearlyWithdrawStatusFailed indicates an expected call of FindYearlyWithdrawStatusFailed.
func (mr *MockWithdrawServiceServerMockRecorder) FindYearlyWithdrawStatusFailed(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindYearlyWithdrawStatusFailed", reflect.TypeOf((*MockWithdrawServiceServer)(nil).FindYearlyWithdrawStatusFailed), arg0, arg1)
}

// FindYearlyWithdrawStatusFailedCardNumber mocks base method.
func (m *MockWithdrawServiceServer) FindYearlyWithdrawStatusFailedCardNumber(arg0 context.Context, arg1 *pb.FindYearWithdrawStatusCardNumber) (*pb.ApiResponseWithdrawYearStatusFailed, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindYearlyWithdrawStatusFailedCardNumber", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawYearStatusFailed)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindYearlyWithdrawStatusFailedCardNumber indicates an expected call of FindYearlyWithdrawStatusFailedCardNumber.
func (mr *MockWithdrawServiceServerMockRecorder) FindYearlyWithdrawStatusFailedCardNumber(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindYearlyWithdrawStatusFailedCardNumber", reflect.TypeOf((*MockWithdrawServiceServer)(nil).FindYearlyWithdrawStatusFailedCardNumber), arg0, arg1)
}

// FindYearlyWithdrawStatusSuccess mocks base method.
func (m *MockWithdrawServiceServer) FindYearlyWithdrawStatusSuccess(arg0 context.Context, arg1 *pb.FindYearWithdrawStatus) (*pb.ApiResponseWithdrawYearStatusSuccess, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindYearlyWithdrawStatusSuccess", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawYearStatusSuccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindYearlyWithdrawStatusSuccess indicates an expected call of FindYearlyWithdrawStatusSuccess.
func (mr *MockWithdrawServiceServerMockRecorder) FindYearlyWithdrawStatusSuccess(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindYearlyWithdrawStatusSuccess", reflect.TypeOf((*MockWithdrawServiceServer)(nil).FindYearlyWithdrawStatusSuccess), arg0, arg1)
}

// FindYearlyWithdrawStatusSuccessCardNumber mocks base method.
func (m *MockWithdrawServiceServer) FindYearlyWithdrawStatusSuccessCardNumber(arg0 context.Context, arg1 *pb.FindYearWithdrawStatusCardNumber) (*pb.ApiResponseWithdrawYearStatusSuccess, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindYearlyWithdrawStatusSuccessCardNumber", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawYearStatusSuccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindYearlyWithdrawStatusSuccessCardNumber indicates an expected call of FindYearlyWithdrawStatusSuccessCardNumber.
func (mr *MockWithdrawServiceServerMockRecorder) FindYearlyWithdrawStatusSuccessCardNumber(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindYearlyWithdrawStatusSuccessCardNumber", reflect.TypeOf((*MockWithdrawServiceServer)(nil).FindYearlyWithdrawStatusSuccessCardNumber), arg0, arg1)
}

// FindYearlyWithdraws mocks base method.
func (m *MockWithdrawServiceServer) FindYearlyWithdraws(arg0 context.Context, arg1 *pb.FindYearWithdrawStatus) (*pb.ApiResponseWithdrawYearAmount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindYearlyWithdraws", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawYearAmount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindYearlyWithdraws indicates an expected call of FindYearlyWithdraws.
func (mr *MockWithdrawServiceServerMockRecorder) FindYearlyWithdraws(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindYearlyWithdraws", reflect.TypeOf((*MockWithdrawServiceServer)(nil).FindYearlyWithdraws), arg0, arg1)
}

// FindYearlyWithdrawsByCardNumber mocks base method.
func (m *MockWithdrawServiceServer) FindYearlyWithdrawsByCardNumber(arg0 context.Context, arg1 *pb.FindYearWithdrawCardNumber) (*pb.ApiResponseWithdrawYearAmount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindYearlyWithdrawsByCardNumber", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawYearAmount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindYearlyWithdrawsByCardNumber indicates an expected call of FindYearlyWithdrawsByCardNumber.
func (mr *MockWithdrawServiceServerMockRecorder) FindYearlyWithdrawsByCardNumber(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindYearlyWithdrawsByCardNumber", reflect.TypeOf((*MockWithdrawServiceServer)(nil).FindYearlyWithdrawsByCardNumber), arg0, arg1)
}

// RestoreAllWithdraw mocks base method.
func (m *MockWithdrawServiceServer) RestoreAllWithdraw(arg0 context.Context, arg1 *emptypb.Empty) (*pb.ApiResponseWithdrawAll, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreAllWithdraw", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseWithdrawAll)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreAllWithdraw indicates an expected call of RestoreAllWithdraw.
func (mr *MockWithdrawServiceServerMockRecorder) RestoreAllWithdraw(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreAllWithdraw", reflect.TypeOf((*MockWithdrawServiceServer)(nil).RestoreAllWithdraw), arg0, arg1)
}

// RestoreWithdraw mocks base method.
func (m *MockWithdrawServiceServer) RestoreWithdraw(arg0 context.Context, arg1 *pb.FindByIdWithdrawRequest) (*pb.ApiResponseWithdraw, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreWithdraw", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseWithdraw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreWithdraw indicates an expected call of RestoreWithdraw.
func (mr *MockWithdrawServiceServerMockRecorder) RestoreWithdraw(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreWithdraw", reflect.TypeOf((*MockWithdrawServiceServer)(nil).RestoreWithdraw), arg0, arg1)
}

// TrashedWithdraw mocks base method.
func (m *MockWithdrawServiceServer) TrashedWithdraw(arg0 context.Context, arg1 *pb.FindByIdWithdrawRequest) (*pb.ApiResponseWithdraw, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrashedWithdraw", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseWithdraw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TrashedWithdraw indicates an expected call of TrashedWithdraw.
func (mr *MockWithdrawServiceServerMockRecorder) TrashedWithdraw(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrashedWithdraw", reflect.TypeOf((*MockWithdrawServiceServer)(nil).TrashedWithdraw), arg0, arg1)
}

// UpdateWithdraw mocks base method.
func (m *MockWithdrawServiceServer) UpdateWithdraw(arg0 context.Context, arg1 *pb.UpdateWithdrawRequest) (*pb.ApiResponseWithdraw, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWithdraw", arg0, arg1)
	ret0, _ := ret[0].(*pb.ApiResponseWithdraw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateWithdraw indicates an expected call of UpdateWithdraw.
func (mr *MockWithdrawServiceServerMockRecorder) UpdateWithdraw(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWithdraw", reflect.TypeOf((*MockWithdrawServiceServer)(nil).UpdateWithdraw), arg0, arg1)
}

// mustEmbedUnimplementedWithdrawServiceServer mocks base method.
func (m *MockWithdrawServiceServer) mustEmbedUnimplementedWithdrawServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedWithdrawServiceServer")
}

// mustEmbedUnimplementedWithdrawServiceServer indicates an expected call of mustEmbedUnimplementedWithdrawServiceServer.
func (mr *MockWithdrawServiceServerMockRecorder) mustEmbedUnimplementedWithdrawServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedWithdrawServiceServer", reflect.TypeOf((*MockWithdrawServiceServer)(nil).mustEmbedUnimplementedWithdrawServiceServer))
}

// MockUnsafeWithdrawServiceServer is a mock of UnsafeWithdrawServiceServer interface.
type MockUnsafeWithdrawServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeWithdrawServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeWithdrawServiceServerMockRecorder is the mock recorder for MockUnsafeWithdrawServiceServer.
type MockUnsafeWithdrawServiceServerMockRecorder struct {
	mock *MockUnsafeWithdrawServiceServer
}

// NewMockUnsafeWithdrawServiceServer creates a new mock instance.
func NewMockUnsafeWithdrawServiceServer(ctrl *gomock.Controller) *MockUnsafeWithdrawServiceServer {
	mock := &MockUnsafeWithdrawServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeWithdrawServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeWithdrawServiceServer) EXPECT() *MockUnsafeWithdrawServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedWithdrawServiceServer mocks base method.
func (m *MockUnsafeWithdrawServiceServer) mustEmbedUnimplementedWithdrawServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedWithdrawServiceServer")
}

// mustEmbedUnimplementedWithdrawServiceServer indicates an expected call of mustEmbedUnimplementedWithdrawServiceServer.
func (mr *MockUnsafeWithdrawServiceServerMockRecorder) mustEmbedUnimplementedWithdrawServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedWithdrawServiceServer", reflect.TypeOf((*MockUnsafeWithdrawServiceServer)(nil).mustEmbedUnimplementedWithdrawServiceServer))
}
