// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.2
// source: transaction.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindByYearCardNumberTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByYearCardNumberTransactionRequest) Reset() {
	*x = FindByYearCardNumberTransactionRequest{}
	mi := &file_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByYearCardNumberTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByYearCardNumberTransactionRequest) ProtoMessage() {}

func (x *FindByYearCardNumberTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByYearCardNumberTransactionRequest.ProtoReflect.Descriptor instead.
func (*FindByYearCardNumberTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *FindByYearCardNumberTransactionRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *FindByYearCardNumberTransactionRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindYearTransactionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearTransactionStatus) Reset() {
	*x = FindYearTransactionStatus{}
	mi := &file_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearTransactionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearTransactionStatus) ProtoMessage() {}

func (x *FindYearTransactionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearTransactionStatus.ProtoReflect.Descriptor instead.
func (*FindYearTransactionStatus) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *FindYearTransactionStatus) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindMonthlyTransactionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"varint,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMonthlyTransactionStatus) Reset() {
	*x = FindMonthlyTransactionStatus{}
	mi := &file_transaction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMonthlyTransactionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMonthlyTransactionStatus) ProtoMessage() {}

func (x *FindMonthlyTransactionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMonthlyTransactionStatus.ProtoReflect.Descriptor instead.
func (*FindMonthlyTransactionStatus) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *FindMonthlyTransactionStatus) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindMonthlyTransactionStatus) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type FindYearTransactionStatusCardNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindYearTransactionStatusCardNumber) Reset() {
	*x = FindYearTransactionStatusCardNumber{}
	mi := &file_transaction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindYearTransactionStatusCardNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindYearTransactionStatusCardNumber) ProtoMessage() {}

func (x *FindYearTransactionStatusCardNumber) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindYearTransactionStatusCardNumber.ProtoReflect.Descriptor instead.
func (*FindYearTransactionStatusCardNumber) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *FindYearTransactionStatusCardNumber) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *FindYearTransactionStatusCardNumber) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type FindMonthlyTransactionStatusCardNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Year          int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"varint,3,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMonthlyTransactionStatusCardNumber) Reset() {
	*x = FindMonthlyTransactionStatusCardNumber{}
	mi := &file_transaction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMonthlyTransactionStatusCardNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMonthlyTransactionStatusCardNumber) ProtoMessage() {}

func (x *FindMonthlyTransactionStatusCardNumber) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMonthlyTransactionStatusCardNumber.ProtoReflect.Descriptor instead.
func (*FindMonthlyTransactionStatusCardNumber) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{4}
}

func (x *FindMonthlyTransactionStatusCardNumber) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *FindMonthlyTransactionStatusCardNumber) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *FindMonthlyTransactionStatusCardNumber) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

type FindAllTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllTransactionRequest) Reset() {
	*x = FindAllTransactionRequest{}
	mi := &file_transaction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllTransactionRequest) ProtoMessage() {}

func (x *FindAllTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllTransactionRequest.ProtoReflect.Descriptor instead.
func (*FindAllTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{5}
}

func (x *FindAllTransactionRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllTransactionRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllTransactionRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindAllTransactionCardNumberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllTransactionCardNumberRequest) Reset() {
	*x = FindAllTransactionCardNumberRequest{}
	mi := &file_transaction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllTransactionCardNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllTransactionCardNumberRequest) ProtoMessage() {}

func (x *FindAllTransactionCardNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllTransactionCardNumberRequest.ProtoReflect.Descriptor instead.
func (*FindAllTransactionCardNumberRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{6}
}

func (x *FindAllTransactionCardNumberRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *FindAllTransactionCardNumberRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FindAllTransactionCardNumberRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *FindAllTransactionCardNumberRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type FindByIdTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId int32                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByIdTransactionRequest) Reset() {
	*x = FindByIdTransactionRequest{}
	mi := &file_transaction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByIdTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByIdTransactionRequest) ProtoMessage() {}

func (x *FindByIdTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByIdTransactionRequest.ProtoReflect.Descriptor instead.
func (*FindByIdTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{7}
}

func (x *FindByIdTransactionRequest) GetTransactionId() int32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

type FindByCardNumberTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CardNumber    string                 `protobuf:"bytes,1,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindByCardNumberTransactionRequest) Reset() {
	*x = FindByCardNumberTransactionRequest{}
	mi := &file_transaction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindByCardNumberTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindByCardNumberTransactionRequest) ProtoMessage() {}

func (x *FindByCardNumberTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindByCardNumberTransactionRequest.ProtoReflect.Descriptor instead.
func (*FindByCardNumberTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{8}
}

func (x *FindByCardNumberTransactionRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

type FindTransactionByMerchantIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    int32                  `protobuf:"varint,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindTransactionByMerchantIdRequest) Reset() {
	*x = FindTransactionByMerchantIdRequest{}
	mi := &file_transaction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindTransactionByMerchantIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindTransactionByMerchantIdRequest) ProtoMessage() {}

func (x *FindTransactionByMerchantIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindTransactionByMerchantIdRequest.ProtoReflect.Descriptor instead.
func (*FindTransactionByMerchantIdRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{9}
}

func (x *FindTransactionByMerchantIdRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

type CreateTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApiKey          string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	CardNumber      string                 `protobuf:"bytes,2,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Amount          int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod   string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	MerchantId      int32                  `protobuf:"varint,5,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	TransactionTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_transaction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{10}
}

func (x *CreateTransactionRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *CreateTransactionRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *CreateTransactionRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *CreateTransactionRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *CreateTransactionRequest) GetTransactionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactionTime
	}
	return nil
}

type UpdateTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   int32                  `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	ApiKey          string                 `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	CardNumber      string                 `protobuf:"bytes,3,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	Amount          int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod   string                 `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	MerchantId      int32                  `protobuf:"varint,6,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	TransactionTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateTransactionRequest) Reset() {
	*x = UpdateTransactionRequest{}
	mi := &file_transaction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionRequest) ProtoMessage() {}

func (x *UpdateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionRequest.ProtoReflect.Descriptor instead.
func (*UpdateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateTransactionRequest) GetTransactionId() int32 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *UpdateTransactionRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *UpdateTransactionRequest) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *UpdateTransactionRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateTransactionRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *UpdateTransactionRequest) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *UpdateTransactionRequest) GetTransactionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.TransactionTime
	}
	return nil
}

type TransactionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CardNumber      string                 `protobuf:"bytes,2,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	TransactionNo   string                 `protobuf:"bytes,3,opt,name=transaction_no,json=transactionNo,proto3" json:"transaction_no,omitempty"`
	Amount          int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod   string                 `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	MerchantId      int32                  `protobuf:"varint,6,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	TransactionTime string                 `protobuf:"bytes,7,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_transaction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{12}
}

func (x *TransactionResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransactionResponse) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *TransactionResponse) GetTransactionNo() string {
	if x != nil {
		return x.TransactionNo
	}
	return ""
}

func (x *TransactionResponse) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *TransactionResponse) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *TransactionResponse) GetTransactionTime() string {
	if x != nil {
		return x.TransactionTime
	}
	return ""
}

func (x *TransactionResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TransactionResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type TransactionResponseDeleteAt struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	Id              int32                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CardNumber      string                  `protobuf:"bytes,2,opt,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	TransactionNo   string                  `protobuf:"bytes,3,opt,name=transaction_no,json=transactionNo,proto3" json:"transaction_no,omitempty"`
	Amount          int32                   `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod   string                  `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	MerchantId      int32                   `protobuf:"varint,6,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	TransactionTime string                  `protobuf:"bytes,7,opt,name=transaction_time,json=transactionTime,proto3" json:"transaction_time,omitempty"`
	CreatedAt       string                  `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       string                  `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt       *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TransactionResponseDeleteAt) Reset() {
	*x = TransactionResponseDeleteAt{}
	mi := &file_transaction_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponseDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponseDeleteAt) ProtoMessage() {}

func (x *TransactionResponseDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponseDeleteAt.ProtoReflect.Descriptor instead.
func (*TransactionResponseDeleteAt) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{13}
}

func (x *TransactionResponseDeleteAt) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransactionResponseDeleteAt) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *TransactionResponseDeleteAt) GetTransactionNo() string {
	if x != nil {
		return x.TransactionNo
	}
	return ""
}

func (x *TransactionResponseDeleteAt) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionResponseDeleteAt) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *TransactionResponseDeleteAt) GetMerchantId() int32 {
	if x != nil {
		return x.MerchantId
	}
	return 0
}

func (x *TransactionResponseDeleteAt) GetTransactionTime() string {
	if x != nil {
		return x.TransactionTime
	}
	return ""
}

func (x *TransactionResponseDeleteAt) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *TransactionResponseDeleteAt) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *TransactionResponseDeleteAt) GetDeletedAt() *wrapperspb.StringValue {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type TransactionMonthStatusSuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         string                 `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	TotalSuccess  int32                  `protobuf:"varint,3,opt,name=total_success,json=totalSuccess,proto3" json:"total_success,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionMonthStatusSuccessResponse) Reset() {
	*x = TransactionMonthStatusSuccessResponse{}
	mi := &file_transaction_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionMonthStatusSuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionMonthStatusSuccessResponse) ProtoMessage() {}

func (x *TransactionMonthStatusSuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionMonthStatusSuccessResponse.ProtoReflect.Descriptor instead.
func (*TransactionMonthStatusSuccessResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{14}
}

func (x *TransactionMonthStatusSuccessResponse) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *TransactionMonthStatusSuccessResponse) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *TransactionMonthStatusSuccessResponse) GetTotalSuccess() int32 {
	if x != nil {
		return x.TotalSuccess
	}
	return 0
}

func (x *TransactionMonthStatusSuccessResponse) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type TransactionYearStatusSuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	TotalSuccess  int32                  `protobuf:"varint,2,opt,name=total_success,json=totalSuccess,proto3" json:"total_success,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionYearStatusSuccessResponse) Reset() {
	*x = TransactionYearStatusSuccessResponse{}
	mi := &file_transaction_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionYearStatusSuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionYearStatusSuccessResponse) ProtoMessage() {}

func (x *TransactionYearStatusSuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionYearStatusSuccessResponse.ProtoReflect.Descriptor instead.
func (*TransactionYearStatusSuccessResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{15}
}

func (x *TransactionYearStatusSuccessResponse) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *TransactionYearStatusSuccessResponse) GetTotalSuccess() int32 {
	if x != nil {
		return x.TotalSuccess
	}
	return 0
}

func (x *TransactionYearStatusSuccessResponse) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type TransactionMonthStatusFailedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         string                 `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
	TotalFailed   int32                  `protobuf:"varint,3,opt,name=total_failed,json=totalFailed,proto3" json:"total_failed,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionMonthStatusFailedResponse) Reset() {
	*x = TransactionMonthStatusFailedResponse{}
	mi := &file_transaction_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionMonthStatusFailedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionMonthStatusFailedResponse) ProtoMessage() {}

func (x *TransactionMonthStatusFailedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionMonthStatusFailedResponse.ProtoReflect.Descriptor instead.
func (*TransactionMonthStatusFailedResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{16}
}

func (x *TransactionMonthStatusFailedResponse) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *TransactionMonthStatusFailedResponse) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *TransactionMonthStatusFailedResponse) GetTotalFailed() int32 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

func (x *TransactionMonthStatusFailedResponse) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type TransactionYearStatusFailedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	TotalFailed   int32                  `protobuf:"varint,2,opt,name=total_failed,json=totalFailed,proto3" json:"total_failed,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionYearStatusFailedResponse) Reset() {
	*x = TransactionYearStatusFailedResponse{}
	mi := &file_transaction_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionYearStatusFailedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionYearStatusFailedResponse) ProtoMessage() {}

func (x *TransactionYearStatusFailedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionYearStatusFailedResponse.ProtoReflect.Descriptor instead.
func (*TransactionYearStatusFailedResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{17}
}

func (x *TransactionYearStatusFailedResponse) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *TransactionYearStatusFailedResponse) GetTotalFailed() int32 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

func (x *TransactionYearStatusFailedResponse) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type TransactionMonthMethodResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Month             string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	PaymentMethod     string                 `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TotalTransactions int32                  `protobuf:"varint,3,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	TotalAmount       int32                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransactionMonthMethodResponse) Reset() {
	*x = TransactionMonthMethodResponse{}
	mi := &file_transaction_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionMonthMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionMonthMethodResponse) ProtoMessage() {}

func (x *TransactionMonthMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionMonthMethodResponse.ProtoReflect.Descriptor instead.
func (*TransactionMonthMethodResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{18}
}

func (x *TransactionMonthMethodResponse) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *TransactionMonthMethodResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *TransactionMonthMethodResponse) GetTotalTransactions() int32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *TransactionMonthMethodResponse) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type TransactionYearMethodResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Year              string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	PaymentMethod     string                 `protobuf:"bytes,2,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	TotalTransactions int32                  `protobuf:"varint,3,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	TotalAmount       int32                  `protobuf:"varint,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransactionYearMethodResponse) Reset() {
	*x = TransactionYearMethodResponse{}
	mi := &file_transaction_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionYearMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionYearMethodResponse) ProtoMessage() {}

func (x *TransactionYearMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionYearMethodResponse.ProtoReflect.Descriptor instead.
func (*TransactionYearMethodResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{19}
}

func (x *TransactionYearMethodResponse) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *TransactionYearMethodResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *TransactionYearMethodResponse) GetTotalTransactions() int32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *TransactionYearMethodResponse) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type TransactionMonthAmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         string                 `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionMonthAmountResponse) Reset() {
	*x = TransactionMonthAmountResponse{}
	mi := &file_transaction_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionMonthAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionMonthAmountResponse) ProtoMessage() {}

func (x *TransactionMonthAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionMonthAmountResponse.ProtoReflect.Descriptor instead.
func (*TransactionMonthAmountResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{20}
}

func (x *TransactionMonthAmountResponse) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

func (x *TransactionMonthAmountResponse) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type TransactionYearlyAmountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          string                 `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,2,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionYearlyAmountResponse) Reset() {
	*x = TransactionYearlyAmountResponse{}
	mi := &file_transaction_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionYearlyAmountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionYearlyAmountResponse) ProtoMessage() {}

func (x *TransactionYearlyAmountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionYearlyAmountResponse.ProtoReflect.Descriptor instead.
func (*TransactionYearlyAmountResponse) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{21}
}

func (x *TransactionYearlyAmountResponse) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *TransactionYearlyAmountResponse) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type ApiResponseTransactionMonthStatusSuccess struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Status        string                                   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                                   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionMonthStatusSuccessResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionMonthStatusSuccess) Reset() {
	*x = ApiResponseTransactionMonthStatusSuccess{}
	mi := &file_transaction_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionMonthStatusSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionMonthStatusSuccess) ProtoMessage() {}

func (x *ApiResponseTransactionMonthStatusSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionMonthStatusSuccess.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionMonthStatusSuccess) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{22}
}

func (x *ApiResponseTransactionMonthStatusSuccess) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionMonthStatusSuccess) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTransactionMonthStatusSuccess) GetData() []*TransactionMonthStatusSuccessResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTransactionYearStatusSuccess struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Status        string                                  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionYearStatusSuccessResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionYearStatusSuccess) Reset() {
	*x = ApiResponseTransactionYearStatusSuccess{}
	mi := &file_transaction_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionYearStatusSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionYearStatusSuccess) ProtoMessage() {}

func (x *ApiResponseTransactionYearStatusSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionYearStatusSuccess.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionYearStatusSuccess) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{23}
}

func (x *ApiResponseTransactionYearStatusSuccess) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionYearStatusSuccess) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTransactionYearStatusSuccess) GetData() []*TransactionYearStatusSuccessResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTransactionMonthStatusFailed struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Status        string                                  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionMonthStatusFailedResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionMonthStatusFailed) Reset() {
	*x = ApiResponseTransactionMonthStatusFailed{}
	mi := &file_transaction_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionMonthStatusFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionMonthStatusFailed) ProtoMessage() {}

func (x *ApiResponseTransactionMonthStatusFailed) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionMonthStatusFailed.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionMonthStatusFailed) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{24}
}

func (x *ApiResponseTransactionMonthStatusFailed) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionMonthStatusFailed) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTransactionMonthStatusFailed) GetData() []*TransactionMonthStatusFailedResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTransactionYearStatusFailed struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Status        string                                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionYearStatusFailedResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionYearStatusFailed) Reset() {
	*x = ApiResponseTransactionYearStatusFailed{}
	mi := &file_transaction_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionYearStatusFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionYearStatusFailed) ProtoMessage() {}

func (x *ApiResponseTransactionYearStatusFailed) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionYearStatusFailed.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionYearStatusFailed) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{25}
}

func (x *ApiResponseTransactionYearStatusFailed) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionYearStatusFailed) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTransactionYearStatusFailed) GetData() []*TransactionYearStatusFailedResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTransactionMonthMethod struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        string                            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionMonthMethodResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionMonthMethod) Reset() {
	*x = ApiResponseTransactionMonthMethod{}
	mi := &file_transaction_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionMonthMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionMonthMethod) ProtoMessage() {}

func (x *ApiResponseTransactionMonthMethod) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionMonthMethod.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionMonthMethod) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{26}
}

func (x *ApiResponseTransactionMonthMethod) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionMonthMethod) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTransactionMonthMethod) GetData() []*TransactionMonthMethodResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTransactionYearMethod struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Status        string                           `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionYearMethodResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionYearMethod) Reset() {
	*x = ApiResponseTransactionYearMethod{}
	mi := &file_transaction_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionYearMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionYearMethod) ProtoMessage() {}

func (x *ApiResponseTransactionYearMethod) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionYearMethod.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionYearMethod) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{27}
}

func (x *ApiResponseTransactionYearMethod) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionYearMethod) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTransactionYearMethod) GetData() []*TransactionYearMethodResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTransactionMonthAmount struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        string                            `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionMonthAmountResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionMonthAmount) Reset() {
	*x = ApiResponseTransactionMonthAmount{}
	mi := &file_transaction_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionMonthAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionMonthAmount) ProtoMessage() {}

func (x *ApiResponseTransactionMonthAmount) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionMonthAmount.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionMonthAmount) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{28}
}

func (x *ApiResponseTransactionMonthAmount) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionMonthAmount) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTransactionMonthAmount) GetData() []*TransactionMonthAmountResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTransactionYearAmount struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Status        string                             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionYearlyAmountResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionYearAmount) Reset() {
	*x = ApiResponseTransactionYearAmount{}
	mi := &file_transaction_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionYearAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionYearAmount) ProtoMessage() {}

func (x *ApiResponseTransactionYearAmount) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionYearAmount.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionYearAmount) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{29}
}

func (x *ApiResponseTransactionYearAmount) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionYearAmount) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTransactionYearAmount) GetData() []*TransactionYearlyAmountResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *TransactionResponse   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransaction) Reset() {
	*x = ApiResponseTransaction{}
	mi := &file_transaction_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransaction) ProtoMessage() {}

func (x *ApiResponseTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransaction.ProtoReflect.Descriptor instead.
func (*ApiResponseTransaction) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{30}
}

func (x *ApiResponseTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransaction) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTransaction) GetData() *TransactionResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTransactions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactions) Reset() {
	*x = ApiResponseTransactions{}
	mi := &file_transaction_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactions) ProtoMessage() {}

func (x *ApiResponseTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactions.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactions) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{31}
}

func (x *ApiResponseTransactions) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactions) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponseTransactions) GetData() []*TransactionResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

type ApiResponseTransactionDelete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionDelete) Reset() {
	*x = ApiResponseTransactionDelete{}
	mi := &file_transaction_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionDelete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionDelete) ProtoMessage() {}

func (x *ApiResponseTransactionDelete) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionDelete.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionDelete) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{32}
}

func (x *ApiResponseTransactionDelete) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionDelete) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponseTransactionAll struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponseTransactionAll) Reset() {
	*x = ApiResponseTransactionAll{}
	mi := &file_transaction_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponseTransactionAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponseTransactionAll) ProtoMessage() {}

func (x *ApiResponseTransactionAll) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponseTransactionAll.ProtoReflect.Descriptor instead.
func (*ApiResponseTransactionAll) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{33}
}

func (x *ApiResponseTransactionAll) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponseTransactionAll) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApiResponsePaginationTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionResponse `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *PaginationMeta        `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationTransaction) Reset() {
	*x = ApiResponsePaginationTransaction{}
	mi := &file_transaction_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationTransaction) ProtoMessage() {}

func (x *ApiResponsePaginationTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationTransaction.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationTransaction) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{34}
}

func (x *ApiResponsePaginationTransaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationTransaction) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationTransaction) GetData() []*TransactionResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationTransaction) GetPagination() *PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ApiResponsePaginationTransactionDeleteAt struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Status        string                         `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          []*TransactionResponseDeleteAt `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *PaginationMeta                `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponsePaginationTransactionDeleteAt) Reset() {
	*x = ApiResponsePaginationTransactionDeleteAt{}
	mi := &file_transaction_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponsePaginationTransactionDeleteAt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponsePaginationTransactionDeleteAt) ProtoMessage() {}

func (x *ApiResponsePaginationTransactionDeleteAt) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponsePaginationTransactionDeleteAt.ProtoReflect.Descriptor instead.
func (*ApiResponsePaginationTransactionDeleteAt) Descriptor() ([]byte, []int) {
	return file_transaction_proto_rawDescGZIP(), []int{35}
}

func (x *ApiResponsePaginationTransactionDeleteAt) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiResponsePaginationTransactionDeleteAt) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponsePaginationTransactionDeleteAt) GetData() []*TransactionResponseDeleteAt {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ApiResponsePaginationTransactionDeleteAt) GetPagination() *PaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_transaction_proto protoreflect.FileDescriptor

const file_transaction_proto_rawDesc = "" +
	"\n" +
	"\x11transaction.proto\x12\x02pb\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\tapi.proto\"]\n" +
	"&FindByYearCardNumberTransactionRequest\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\"/\n" +
	"\x19FindYearTransactionStatus\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\"H\n" +
	"\x1cFindMonthlyTransactionStatus\x12\x12\n" +
	"\x04year\x18\x01 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\"Z\n" +
	"#FindYearTransactionStatusCardNumber\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\"s\n" +
	"&FindMonthlyTransactionStatusCardNumber\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x14\n" +
	"\x05month\x18\x03 \x01(\x05R\x05month\"d\n" +
	"\x19FindAllTransactionRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\"\x8f\x01\n" +
	"#FindAllTransactionCardNumberRequest\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\"C\n" +
	"\x1aFindByIdTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x05R\rtransactionId\"E\n" +
	"\"FindByCardNumberTransactionRequest\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\"E\n" +
	"\"FindTransactionByMerchantIdRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\x05R\n" +
	"merchantId\"\xfb\x01\n" +
	"\x18CreateTransactionRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x1f\n" +
	"\vcard_number\x18\x02 \x01(\tR\n" +
	"cardNumber\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\x12\x1f\n" +
	"\vmerchant_id\x18\x05 \x01(\x05R\n" +
	"merchantId\x12E\n" +
	"\x10transaction_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0ftransactionTime\"\xa2\x02\n" +
	"\x18UpdateTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\x05R\rtransactionId\x12\x17\n" +
	"\aapi_key\x18\x02 \x01(\tR\x06apiKey\x12\x1f\n" +
	"\vcard_number\x18\x03 \x01(\tR\n" +
	"cardNumber\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\x12%\n" +
	"\x0epayment_method\x18\x05 \x01(\tR\rpaymentMethod\x12\x1f\n" +
	"\vmerchant_id\x18\x06 \x01(\x05R\n" +
	"merchantId\x12E\n" +
	"\x10transaction_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0ftransactionTime\"\xb6\x02\n" +
	"\x13TransactionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vcard_number\x18\x02 \x01(\tR\n" +
	"cardNumber\x12%\n" +
	"\x0etransaction_no\x18\x03 \x01(\tR\rtransactionNo\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\x12%\n" +
	"\x0epayment_method\x18\x05 \x01(\tR\rpaymentMethod\x12\x1f\n" +
	"\vmerchant_id\x18\x06 \x01(\x05R\n" +
	"merchantId\x12)\n" +
	"\x10transaction_time\x18\a \x01(\tR\x0ftransactionTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\xfb\x02\n" +
	"\x1bTransactionResponseDeleteAt\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vcard_number\x18\x02 \x01(\tR\n" +
	"cardNumber\x12%\n" +
	"\x0etransaction_no\x18\x03 \x01(\tR\rtransactionNo\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\x12%\n" +
	"\x0epayment_method\x18\x05 \x01(\tR\rpaymentMethod\x12\x1f\n" +
	"\vmerchant_id\x18\x06 \x01(\x05R\n" +
	"merchantId\x12)\n" +
	"\x10transaction_time\x18\a \x01(\tR\x0ftransactionTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12;\n" +
	"\n" +
	"deleted_at\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\tdeletedAt\"\x99\x01\n" +
	"%TransactionMonthStatusSuccessResponse\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\tR\x05month\x12#\n" +
	"\rtotal_success\x18\x03 \x01(\x05R\ftotalSuccess\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x05R\vtotalAmount\"\x82\x01\n" +
	"$TransactionYearStatusSuccessResponse\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12#\n" +
	"\rtotal_success\x18\x02 \x01(\x05R\ftotalSuccess\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x05R\vtotalAmount\"\x96\x01\n" +
	"$TransactionMonthStatusFailedResponse\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12\x14\n" +
	"\x05month\x18\x02 \x01(\tR\x05month\x12!\n" +
	"\ftotal_failed\x18\x03 \x01(\x05R\vtotalFailed\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x05R\vtotalAmount\"\x7f\n" +
	"#TransactionYearStatusFailedResponse\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12!\n" +
	"\ftotal_failed\x18\x02 \x01(\x05R\vtotalFailed\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x05R\vtotalAmount\"\xaf\x01\n" +
	"\x1eTransactionMonthMethodResponse\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12%\n" +
	"\x0epayment_method\x18\x02 \x01(\tR\rpaymentMethod\x12-\n" +
	"\x12total_transactions\x18\x03 \x01(\x05R\x11totalTransactions\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x05R\vtotalAmount\"\xac\x01\n" +
	"\x1dTransactionYearMethodResponse\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12%\n" +
	"\x0epayment_method\x18\x02 \x01(\tR\rpaymentMethod\x12-\n" +
	"\x12total_transactions\x18\x03 \x01(\x05R\x11totalTransactions\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x05R\vtotalAmount\"Y\n" +
	"\x1eTransactionMonthAmountResponse\x12\x14\n" +
	"\x05month\x18\x01 \x01(\tR\x05month\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x05R\vtotalAmount\"X\n" +
	"\x1fTransactionYearlyAmountResponse\x12\x12\n" +
	"\x04year\x18\x01 \x01(\tR\x04year\x12!\n" +
	"\ftotal_amount\x18\x02 \x01(\x05R\vtotalAmount\"\x9b\x01\n" +
	"(ApiResponseTransactionMonthStatusSuccess\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\x04data\x18\x03 \x03(\v2).pb.TransactionMonthStatusSuccessResponseR\x04data\"\x99\x01\n" +
	"'ApiResponseTransactionYearStatusSuccess\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\x04data\x18\x03 \x03(\v2(.pb.TransactionYearStatusSuccessResponseR\x04data\"\x99\x01\n" +
	"'ApiResponseTransactionMonthStatusFailed\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\x04data\x18\x03 \x03(\v2(.pb.TransactionMonthStatusFailedResponseR\x04data\"\x97\x01\n" +
	"&ApiResponseTransactionYearStatusFailed\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12;\n" +
	"\x04data\x18\x03 \x03(\v2'.pb.TransactionYearStatusFailedResponseR\x04data\"\x8d\x01\n" +
	"!ApiResponseTransactionMonthMethod\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\x04data\x18\x03 \x03(\v2\".pb.TransactionMonthMethodResponseR\x04data\"\x8b\x01\n" +
	" ApiResponseTransactionYearMethod\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\x04data\x18\x03 \x03(\v2!.pb.TransactionYearMethodResponseR\x04data\"\x8d\x01\n" +
	"!ApiResponseTransactionMonthAmount\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x126\n" +
	"\x04data\x18\x03 \x03(\v2\".pb.TransactionMonthAmountResponseR\x04data\"\x8d\x01\n" +
	" ApiResponseTransactionYearAmount\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x127\n" +
	"\x04data\x18\x03 \x03(\v2#.pb.TransactionYearlyAmountResponseR\x04data\"w\n" +
	"\x16ApiResponseTransaction\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.pb.TransactionResponseR\x04data\"x\n" +
	"\x17ApiResponseTransactions\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x03(\v2\x17.pb.TransactionResponseR\x04data\"P\n" +
	"\x1cApiResponseTransactionDelete\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"M\n" +
	"\x19ApiResponseTransactionAll\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xb5\x01\n" +
	" ApiResponsePaginationTransaction\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x04data\x18\x03 \x03(\v2\x17.pb.TransactionResponseR\x04data\x122\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.pb.PaginationMetaR\n" +
	"pagination\"\xc5\x01\n" +
	"(ApiResponsePaginationTransactionDeleteAt\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x123\n" +
	"\x04data\x18\x03 \x03(\v2\x1f.pb.TransactionResponseDeleteAtR\x04data\x122\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x12.pb.PaginationMetaR\n" +
	"pagination2\xa6\x18\n" +
	"\x12TransactionService\x12Y\n" +
	"\x12FindAllTransaction\x12\x1d.pb.FindAllTransactionRequest\x1a$.pb.ApiResponsePaginationTransaction\x12o\n" +
	"\x1eFindAllTransactionByCardNumber\x12'.pb.FindAllTransactionCardNumberRequest\x1a$.pb.ApiResponsePaginationTransaction\x12Q\n" +
	"\x13FindByIdTransaction\x12\x1e.pb.FindByIdTransactionRequest\x1a\x1a.pb.ApiResponseTransaction\x12w\n" +
	"#FindMonthlyTransactionStatusSuccess\x12 .pb.FindMonthlyTransactionStatus\x1a,.pb.ApiResponseTransactionMonthStatusSuccess\"\x00\x12r\n" +
	"\"FindYearlyTransactionStatusSuccess\x12\x1d.pb.FindYearTransactionStatus\x1a+.pb.ApiResponseTransactionYearStatusSuccess\"\x00\x12u\n" +
	"\"FindMonthlyTransactionStatusFailed\x12 .pb.FindMonthlyTransactionStatus\x1a+.pb.ApiResponseTransactionMonthStatusFailed\"\x00\x12p\n" +
	"!FindYearlyTransactionStatusFailed\x12\x1d.pb.FindYearTransactionStatus\x1a*.pb.ApiResponseTransactionYearStatusFailed\"\x00\x12\x8d\x01\n" +
	"/FindMonthlyTransactionStatusSuccessByCardNumber\x12*.pb.FindMonthlyTransactionStatusCardNumber\x1a,.pb.ApiResponseTransactionMonthStatusSuccess\"\x00\x12\x88\x01\n" +
	".FindYearlyTransactionStatusSuccessByCardNumber\x12'.pb.FindYearTransactionStatusCardNumber\x1a+.pb.ApiResponseTransactionYearStatusSuccess\"\x00\x12\x8b\x01\n" +
	".FindMonthlyTransactionStatusFailedByCardNumber\x12*.pb.FindMonthlyTransactionStatusCardNumber\x1a+.pb.ApiResponseTransactionMonthStatusFailed\"\x00\x12\x86\x01\n" +
	"-FindYearlyTransactionStatusFailedByCardNumber\x12'.pb.FindYearTransactionStatusCardNumber\x1a*.pb.ApiResponseTransactionYearStatusFailed\"\x00\x12c\n" +
	"\x19FindMonthlyPaymentMethods\x12\x1d.pb.FindYearTransactionStatus\x1a%.pb.ApiResponseTransactionMonthMethod\"\x00\x12a\n" +
	"\x18FindYearlyPaymentMethods\x12\x1d.pb.FindYearTransactionStatus\x1a$.pb.ApiResponseTransactionYearMethod\"\x00\x12\\\n" +
	"\x12FindMonthlyAmounts\x12\x1d.pb.FindYearTransactionStatus\x1a%.pb.ApiResponseTransactionMonthAmount\"\x00\x12Z\n" +
	"\x11FindYearlyAmounts\x12\x1d.pb.FindYearTransactionStatus\x1a$.pb.ApiResponseTransactionYearAmount\"\x00\x12|\n" +
	"%FindMonthlyPaymentMethodsByCardNumber\x12*.pb.FindByYearCardNumberTransactionRequest\x1a%.pb.ApiResponseTransactionMonthMethod\"\x00\x12z\n" +
	"$FindYearlyPaymentMethodsByCardNumber\x12*.pb.FindByYearCardNumberTransactionRequest\x1a$.pb.ApiResponseTransactionYearMethod\"\x00\x12u\n" +
	"\x1eFindMonthlyAmountsByCardNumber\x12*.pb.FindByYearCardNumberTransactionRequest\x1a%.pb.ApiResponseTransactionMonthAmount\"\x00\x12s\n" +
	"\x1dFindYearlyAmountsByCardNumber\x12*.pb.FindByYearCardNumberTransactionRequest\x1a$.pb.ApiResponseTransactionYearAmount\"\x00\x12b\n" +
	"\x1bFindTransactionByMerchantId\x12&.pb.FindTransactionByMerchantIdRequest\x1a\x1b.pb.ApiResponseTransactions\x12f\n" +
	"\x17FindByActiveTransaction\x12\x1d.pb.FindAllTransactionRequest\x1a,.pb.ApiResponsePaginationTransactionDeleteAt\x12g\n" +
	"\x18FindByTrashedTransaction\x12\x1d.pb.FindAllTransactionRequest\x1a,.pb.ApiResponsePaginationTransactionDeleteAt\x12M\n" +
	"\x11CreateTransaction\x12\x1c.pb.CreateTransactionRequest\x1a\x1a.pb.ApiResponseTransaction\x12M\n" +
	"\x11UpdateTransaction\x12\x1c.pb.UpdateTransactionRequest\x1a\x1a.pb.ApiResponseTransaction\x12P\n" +
	"\x12TrashedTransaction\x12\x1e.pb.FindByIdTransactionRequest\x1a\x1a.pb.ApiResponseTransaction\x12P\n" +
	"\x12RestoreTransaction\x12\x1e.pb.FindByIdTransactionRequest\x1a\x1a.pb.ApiResponseTransaction\x12^\n" +
	"\x1aDeleteTransactionPermanent\x12\x1e.pb.FindByIdTransactionRequest\x1a .pb.ApiResponseTransactionDelete\x12P\n" +
	"\x15RestoreAllTransaction\x12\x16.google.protobuf.Empty\x1a\x1d.pb.ApiResponseTransactionAll\"\x00\x12X\n" +
	"\x1dDeleteAllTransactionPermanent\x12\x16.google.protobuf.Empty\x1a\x1d.pb.ApiResponseTransactionAll\"\x00B+Z)MamangRust/paymentgatewaygrpc/internal/pbb\x06proto3"

var (
	file_transaction_proto_rawDescOnce sync.Once
	file_transaction_proto_rawDescData []byte
)

func file_transaction_proto_rawDescGZIP() []byte {
	file_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)))
	})
	return file_transaction_proto_rawDescData
}

var file_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_transaction_proto_goTypes = []any{
	(*FindByYearCardNumberTransactionRequest)(nil),   // 0: pb.FindByYearCardNumberTransactionRequest
	(*FindYearTransactionStatus)(nil),                // 1: pb.FindYearTransactionStatus
	(*FindMonthlyTransactionStatus)(nil),             // 2: pb.FindMonthlyTransactionStatus
	(*FindYearTransactionStatusCardNumber)(nil),      // 3: pb.FindYearTransactionStatusCardNumber
	(*FindMonthlyTransactionStatusCardNumber)(nil),   // 4: pb.FindMonthlyTransactionStatusCardNumber
	(*FindAllTransactionRequest)(nil),                // 5: pb.FindAllTransactionRequest
	(*FindAllTransactionCardNumberRequest)(nil),      // 6: pb.FindAllTransactionCardNumberRequest
	(*FindByIdTransactionRequest)(nil),               // 7: pb.FindByIdTransactionRequest
	(*FindByCardNumberTransactionRequest)(nil),       // 8: pb.FindByCardNumberTransactionRequest
	(*FindTransactionByMerchantIdRequest)(nil),       // 9: pb.FindTransactionByMerchantIdRequest
	(*CreateTransactionRequest)(nil),                 // 10: pb.CreateTransactionRequest
	(*UpdateTransactionRequest)(nil),                 // 11: pb.UpdateTransactionRequest
	(*TransactionResponse)(nil),                      // 12: pb.TransactionResponse
	(*TransactionResponseDeleteAt)(nil),              // 13: pb.TransactionResponseDeleteAt
	(*TransactionMonthStatusSuccessResponse)(nil),    // 14: pb.TransactionMonthStatusSuccessResponse
	(*TransactionYearStatusSuccessResponse)(nil),     // 15: pb.TransactionYearStatusSuccessResponse
	(*TransactionMonthStatusFailedResponse)(nil),     // 16: pb.TransactionMonthStatusFailedResponse
	(*TransactionYearStatusFailedResponse)(nil),      // 17: pb.TransactionYearStatusFailedResponse
	(*TransactionMonthMethodResponse)(nil),           // 18: pb.TransactionMonthMethodResponse
	(*TransactionYearMethodResponse)(nil),            // 19: pb.TransactionYearMethodResponse
	(*TransactionMonthAmountResponse)(nil),           // 20: pb.TransactionMonthAmountResponse
	(*TransactionYearlyAmountResponse)(nil),          // 21: pb.TransactionYearlyAmountResponse
	(*ApiResponseTransactionMonthStatusSuccess)(nil), // 22: pb.ApiResponseTransactionMonthStatusSuccess
	(*ApiResponseTransactionYearStatusSuccess)(nil),  // 23: pb.ApiResponseTransactionYearStatusSuccess
	(*ApiResponseTransactionMonthStatusFailed)(nil),  // 24: pb.ApiResponseTransactionMonthStatusFailed
	(*ApiResponseTransactionYearStatusFailed)(nil),   // 25: pb.ApiResponseTransactionYearStatusFailed
	(*ApiResponseTransactionMonthMethod)(nil),        // 26: pb.ApiResponseTransactionMonthMethod
	(*ApiResponseTransactionYearMethod)(nil),         // 27: pb.ApiResponseTransactionYearMethod
	(*ApiResponseTransactionMonthAmount)(nil),        // 28: pb.ApiResponseTransactionMonthAmount
	(*ApiResponseTransactionYearAmount)(nil),         // 29: pb.ApiResponseTransactionYearAmount
	(*ApiResponseTransaction)(nil),                   // 30: pb.ApiResponseTransaction
	(*ApiResponseTransactions)(nil),                  // 31: pb.ApiResponseTransactions
	(*ApiResponseTransactionDelete)(nil),             // 32: pb.ApiResponseTransactionDelete
	(*ApiResponseTransactionAll)(nil),                // 33: pb.ApiResponseTransactionAll
	(*ApiResponsePaginationTransaction)(nil),         // 34: pb.ApiResponsePaginationTransaction
	(*ApiResponsePaginationTransactionDeleteAt)(nil), // 35: pb.ApiResponsePaginationTransactionDeleteAt
	(*timestamppb.Timestamp)(nil),                    // 36: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil),                   // 37: google.protobuf.StringValue
	(*PaginationMeta)(nil),                           // 38: pb.PaginationMeta
	(*emptypb.Empty)(nil),                            // 39: google.protobuf.Empty
}
var file_transaction_proto_depIdxs = []int32{
	36, // 0: pb.CreateTransactionRequest.transaction_time:type_name -> google.protobuf.Timestamp
	36, // 1: pb.UpdateTransactionRequest.transaction_time:type_name -> google.protobuf.Timestamp
	37, // 2: pb.TransactionResponseDeleteAt.deleted_at:type_name -> google.protobuf.StringValue
	14, // 3: pb.ApiResponseTransactionMonthStatusSuccess.data:type_name -> pb.TransactionMonthStatusSuccessResponse
	15, // 4: pb.ApiResponseTransactionYearStatusSuccess.data:type_name -> pb.TransactionYearStatusSuccessResponse
	16, // 5: pb.ApiResponseTransactionMonthStatusFailed.data:type_name -> pb.TransactionMonthStatusFailedResponse
	17, // 6: pb.ApiResponseTransactionYearStatusFailed.data:type_name -> pb.TransactionYearStatusFailedResponse
	18, // 7: pb.ApiResponseTransactionMonthMethod.data:type_name -> pb.TransactionMonthMethodResponse
	19, // 8: pb.ApiResponseTransactionYearMethod.data:type_name -> pb.TransactionYearMethodResponse
	20, // 9: pb.ApiResponseTransactionMonthAmount.data:type_name -> pb.TransactionMonthAmountResponse
	21, // 10: pb.ApiResponseTransactionYearAmount.data:type_name -> pb.TransactionYearlyAmountResponse
	12, // 11: pb.ApiResponseTransaction.data:type_name -> pb.TransactionResponse
	12, // 12: pb.ApiResponseTransactions.data:type_name -> pb.TransactionResponse
	12, // 13: pb.ApiResponsePaginationTransaction.data:type_name -> pb.TransactionResponse
	38, // 14: pb.ApiResponsePaginationTransaction.pagination:type_name -> pb.PaginationMeta
	13, // 15: pb.ApiResponsePaginationTransactionDeleteAt.data:type_name -> pb.TransactionResponseDeleteAt
	38, // 16: pb.ApiResponsePaginationTransactionDeleteAt.pagination:type_name -> pb.PaginationMeta
	5,  // 17: pb.TransactionService.FindAllTransaction:input_type -> pb.FindAllTransactionRequest
	6,  // 18: pb.TransactionService.FindAllTransactionByCardNumber:input_type -> pb.FindAllTransactionCardNumberRequest
	7,  // 19: pb.TransactionService.FindByIdTransaction:input_type -> pb.FindByIdTransactionRequest
	2,  // 20: pb.TransactionService.FindMonthlyTransactionStatusSuccess:input_type -> pb.FindMonthlyTransactionStatus
	1,  // 21: pb.TransactionService.FindYearlyTransactionStatusSuccess:input_type -> pb.FindYearTransactionStatus
	2,  // 22: pb.TransactionService.FindMonthlyTransactionStatusFailed:input_type -> pb.FindMonthlyTransactionStatus
	1,  // 23: pb.TransactionService.FindYearlyTransactionStatusFailed:input_type -> pb.FindYearTransactionStatus
	4,  // 24: pb.TransactionService.FindMonthlyTransactionStatusSuccessByCardNumber:input_type -> pb.FindMonthlyTransactionStatusCardNumber
	3,  // 25: pb.TransactionService.FindYearlyTransactionStatusSuccessByCardNumber:input_type -> pb.FindYearTransactionStatusCardNumber
	4,  // 26: pb.TransactionService.FindMonthlyTransactionStatusFailedByCardNumber:input_type -> pb.FindMonthlyTransactionStatusCardNumber
	3,  // 27: pb.TransactionService.FindYearlyTransactionStatusFailedByCardNumber:input_type -> pb.FindYearTransactionStatusCardNumber
	1,  // 28: pb.TransactionService.FindMonthlyPaymentMethods:input_type -> pb.FindYearTransactionStatus
	1,  // 29: pb.TransactionService.FindYearlyPaymentMethods:input_type -> pb.FindYearTransactionStatus
	1,  // 30: pb.TransactionService.FindMonthlyAmounts:input_type -> pb.FindYearTransactionStatus
	1,  // 31: pb.TransactionService.FindYearlyAmounts:input_type -> pb.FindYearTransactionStatus
	0,  // 32: pb.TransactionService.FindMonthlyPaymentMethodsByCardNumber:input_type -> pb.FindByYearCardNumberTransactionRequest
	0,  // 33: pb.TransactionService.FindYearlyPaymentMethodsByCardNumber:input_type -> pb.FindByYearCardNumberTransactionRequest
	0,  // 34: pb.TransactionService.FindMonthlyAmountsByCardNumber:input_type -> pb.FindByYearCardNumberTransactionRequest
	0,  // 35: pb.TransactionService.FindYearlyAmountsByCardNumber:input_type -> pb.FindByYearCardNumberTransactionRequest
	9,  // 36: pb.TransactionService.FindTransactionByMerchantId:input_type -> pb.FindTransactionByMerchantIdRequest
	5,  // 37: pb.TransactionService.FindByActiveTransaction:input_type -> pb.FindAllTransactionRequest
	5,  // 38: pb.TransactionService.FindByTrashedTransaction:input_type -> pb.FindAllTransactionRequest
	10, // 39: pb.TransactionService.CreateTransaction:input_type -> pb.CreateTransactionRequest
	11, // 40: pb.TransactionService.UpdateTransaction:input_type -> pb.UpdateTransactionRequest
	7,  // 41: pb.TransactionService.TrashedTransaction:input_type -> pb.FindByIdTransactionRequest
	7,  // 42: pb.TransactionService.RestoreTransaction:input_type -> pb.FindByIdTransactionRequest
	7,  // 43: pb.TransactionService.DeleteTransactionPermanent:input_type -> pb.FindByIdTransactionRequest
	39, // 44: pb.TransactionService.RestoreAllTransaction:input_type -> google.protobuf.Empty
	39, // 45: pb.TransactionService.DeleteAllTransactionPermanent:input_type -> google.protobuf.Empty
	34, // 46: pb.TransactionService.FindAllTransaction:output_type -> pb.ApiResponsePaginationTransaction
	34, // 47: pb.TransactionService.FindAllTransactionByCardNumber:output_type -> pb.ApiResponsePaginationTransaction
	30, // 48: pb.TransactionService.FindByIdTransaction:output_type -> pb.ApiResponseTransaction
	22, // 49: pb.TransactionService.FindMonthlyTransactionStatusSuccess:output_type -> pb.ApiResponseTransactionMonthStatusSuccess
	23, // 50: pb.TransactionService.FindYearlyTransactionStatusSuccess:output_type -> pb.ApiResponseTransactionYearStatusSuccess
	24, // 51: pb.TransactionService.FindMonthlyTransactionStatusFailed:output_type -> pb.ApiResponseTransactionMonthStatusFailed
	25, // 52: pb.TransactionService.FindYearlyTransactionStatusFailed:output_type -> pb.ApiResponseTransactionYearStatusFailed
	22, // 53: pb.TransactionService.FindMonthlyTransactionStatusSuccessByCardNumber:output_type -> pb.ApiResponseTransactionMonthStatusSuccess
	23, // 54: pb.TransactionService.FindYearlyTransactionStatusSuccessByCardNumber:output_type -> pb.ApiResponseTransactionYearStatusSuccess
	24, // 55: pb.TransactionService.FindMonthlyTransactionStatusFailedByCardNumber:output_type -> pb.ApiResponseTransactionMonthStatusFailed
	25, // 56: pb.TransactionService.FindYearlyTransactionStatusFailedByCardNumber:output_type -> pb.ApiResponseTransactionYearStatusFailed
	26, // 57: pb.TransactionService.FindMonthlyPaymentMethods:output_type -> pb.ApiResponseTransactionMonthMethod
	27, // 58: pb.TransactionService.FindYearlyPaymentMethods:output_type -> pb.ApiResponseTransactionYearMethod
	28, // 59: pb.TransactionService.FindMonthlyAmounts:output_type -> pb.ApiResponseTransactionMonthAmount
	29, // 60: pb.TransactionService.FindYearlyAmounts:output_type -> pb.ApiResponseTransactionYearAmount
	26, // 61: pb.TransactionService.FindMonthlyPaymentMethodsByCardNumber:output_type -> pb.ApiResponseTransactionMonthMethod
	27, // 62: pb.TransactionService.FindYearlyPaymentMethodsByCardNumber:output_type -> pb.ApiResponseTransactionYearMethod
	28, // 63: pb.TransactionService.FindMonthlyAmountsByCardNumber:output_type -> pb.ApiResponseTransactionMonthAmount
	29, // 64: pb.TransactionService.FindYearlyAmountsByCardNumber:output_type -> pb.ApiResponseTransactionYearAmount
	31, // 65: pb.TransactionService.FindTransactionByMerchantId:output_type -> pb.ApiResponseTransactions
	35, // 66: pb.TransactionService.FindByActiveTransaction:output_type -> pb.ApiResponsePaginationTransactionDeleteAt
	35, // 67: pb.TransactionService.FindByTrashedTransaction:output_type -> pb.ApiResponsePaginationTransactionDeleteAt
	30, // 68: pb.TransactionService.CreateTransaction:output_type -> pb.ApiResponseTransaction
	30, // 69: pb.TransactionService.UpdateTransaction:output_type -> pb.ApiResponseTransaction
	30, // 70: pb.TransactionService.TrashedTransaction:output_type -> pb.ApiResponseTransaction
	30, // 71: pb.TransactionService.RestoreTransaction:output_type -> pb.ApiResponseTransaction
	32, // 72: pb.TransactionService.DeleteTransactionPermanent:output_type -> pb.ApiResponseTransactionDelete
	33, // 73: pb.TransactionService.RestoreAllTransaction:output_type -> pb.ApiResponseTransactionAll
	33, // 74: pb.TransactionService.DeleteAllTransactionPermanent:output_type -> pb.ApiResponseTransactionAll
	46, // [46:75] is the sub-list for method output_type
	17, // [17:46] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_transaction_proto_init() }
func file_transaction_proto_init() {
	if File_transaction_proto != nil {
		return
	}
	file_api_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_proto_rawDesc), len(file_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_proto_depIdxs,
		MessageInfos:      file_transaction_proto_msgTypes,
	}.Build()
	File_transaction_proto = out.File
	file_transaction_proto_goTypes = nil
	file_transaction_proto_depIdxs = nil
}
